

spring:
  application:
    name: shop-base-service
  profiles:
    active: dev

logging:
  config: classpath:logback.xml
  level:
    org:
      springframework:
        web: info

# sql xml文件位置
mybatis:
  mapper-locations: classpath*:mybatis/*.xml,classpath*:mybatis/*/*.xml

jwt:
  config:
    key: shop
    ttl: 3600000