server:
  port: 9002


spring:
  main:
    allow-bean-definition-overriding: true # 允许bean定义覆盖

  application:
    name: shop-gateway-service
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848 # nacos配置中心地址
      discovery:
        server-addr: 127.0.0.1:8848 # nacos注册中心地址
    gateway:
      discovery:
        locator:
          enabled: true # 是否与服务发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
  # DB
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource


logging: # 配置输出日志
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
        http:
          server:
            reactive: DEBUG
        web:
          reactive: DEBUG
    reactor:
      ipc:
        netty: DEBUG

management: #开启端点监控
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"


